CREATE DATABASE camagru_mrakhman;




CREATE TABLE passReset (
	id int(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	email TEXT NOT NULL,
	selector TEXT NOT NULL,
	token LONGTEXT NOT NULL,
	expires TEXT NOT NULL
);